### ISSUE TITLE
os1 on windows

### ISSUE THREAD

**Issue by ThibaudMZN** [AlejandroSilvestri/os1#13]
I've successfully installed ORB-SLAM2 on windows, but i need to use a fisheye camera, so i want to try this os1 version. Do you have any hints on how i can use your code without having to recompile everything ? I guess if it's a Linux version, i'll have some compatibility issues.

Thanks a lot,
Thibaud

**Comment by AlejandroSilvestri** [comment]
@ThibaudMZN 
Look for antidistorsionarProyeccionEquidistante(...) in
https://github.com/AlejandroSilvestri/os1/blob/PuntosLejanos/src/Frame.cc#L355

This works like cv::undistortPoints(...) , but using equidistant projection.  OpenCV has it, I copy the code because an odd error prevented me for using its function directly.  So, antidistorsionarProyeccionEquidistante(...) is basically a copy from opencv code.

**Comment by AlejandroSilvestri** [comment]
@ThibaudMZN 

os1 is no compatible con Windows.  For one, it uses zenity for dialog windows.  To port to Windows a very little code touching is necessary.
