### ISSUE TITLE
ORB_SLAM2::ORBVocabulary has no member named 'LoadFromBinaryFile;

### ISSUE THREAD

**Issue by Jephinus** [AlejandroSilvestri/os1#14]
Hi! I have met this error when I 'make' this folder. Fail in compiling at the beginning. Anyone help is much appreciated.

**Comment by AlejandroSilvestri** [comment]
Hi @Jephinus ,

It is defined here:
https://github.com/AlejandroSilvestri/os1/blob/PuntosLejanos/Thirdparty/DBoW2/DBoW2/TemplatedVocabulary.h#L1563

I don't know why the error.

If you are mixing files from OS1 and ORB_SLAM, beware that it is not a good idea.  OS1 is monocular only.  If you are ok with that, use OS1 instead of ORB_SLAM2.  It uses the same vocabulary, but compressed in binary format for fast start up.  You'll find the message "this could take a while" a little odd.

**Comment by Jephinus** [comment]
Hi @AlejandroSilvestri ,

Thank you for your help.
Sorry, I know I am new to this, but I have no idea how to compile OS1 and how to execute the OS1 in terminal. Can you perhaps guide me through the steps? Thank you very much.

**Comment by AlejandroSilvestri** [comment]
@Jephinus , I updated the default branch, now it is Video, no more master nor PuntosLejanos, please download the project from there.

Nothing changed about LoadFromBinaryFile.

**Comment by Jephinus** [comment]
@AlejandroSilvestri , Okay. But the same problem is how do I compile this file? And how can i execute this file. As in ORB-SLAM2, i can run by using the following command: ./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUMX.yaml PATH_TO_SEQUENCE_FOLDER

How about OS1?

**Comment by AlejandroSilvestri** [comment]
os1 is the executable file.

    os1 
opens webcam using webcam.yaml as configuration file.

    os1 conf.yaml video.mp4
opens video.mp4 using conf.yaml as configuration file.

**Comment by Jephinus** [comment]
When I type in the command, errors are shown. I don't see any executable
file. In my experience, executable file will only appear after compilation,
right ?

**Comment by AlejandroSilvestri** [comment]
@Jephinus , right.

This code is expected to be compiled and run from an IDE.

I hope a collaborator will provide us a cmake file soon, for easy installation.
