### ISSUE TITLE
can it work fine for stereo case?

### ISSUE THREAD

**Issue by pengjq** [AlejandroSilvestri/os1#20]
I'm very interested in this work, you said that it works well for monocular case, but can it work for stereo case? 
thank you.

**Comment by AlejandroSilvestri** [comment]
The main added function in os1 is its ability to save and load maps.  The implemented map file format ignores everything related to stereo.

In order to make it work in setreo or rgbd, you (or somebody) have to modify the serializer code, easy work if you're lucky it works in the first try, hard work otherwise.

os1 development is paused right now.  An advanced student is working in a new, better coded and well documented version of orb-slam2, that will replace os1.  After this I hope we can address a complete map serialization, with stereo and rgbd support.

**Comment by pengjq** [comment]
ok thank you very much.
