### ISSUE TITLE
Scale error

### ISSUE THREAD

**Issue by ghost** [AlejandroSilvestri/os1#22]
I am using the stereo version of ORBSLAM 2, but the scale will always increase by about 10%. By the way, when using other stereo cameras the scale will be reduced by about 10%. I use the OpenCV fisheye calibration API.

I heard that the scale of the monocular version of ORBSLAM 2 was determined at the time of initialization and then the scale drift began. How does scale error occur in the stereo version of ORBSLAM 2?
Is there any countermeasure?

**Comment by AlejandroSilvestri** [comment]
@takuhara ,

This project is about monocular.  I think you'll get better answers at ORB-SLAM2 repository's issues.
I do not know what scale are you talking about.  I'm not sure if ORB-SLAM2 has fisheye calibration.

**Comment by ghost** [comment]
I am confronted with the problem that the scale of the map always grows large.
Since the scale of the monocular map is determined during the initialization, initialization is considered important.
I would like to know whether the scale of the map in stereo is also determined during initialization. I want to know if it is the same mechanism between stereo and monocular.

>I think you'll get better answers at ORB-SLAM2 repository's issues.

thanx!

**Comment by AlejandroSilvestri** [comment]
You can't get scale from monocular, it hasn't any real size reference.  Monocular uses arbitrary scale defined on initialization, beyond user's control.  Two initializations on the same scene can lead to different scales.

Stereo otherwise uses the known distance between both cameras as reference, so all the map can be expressed in terms of cameras distance.  Knowing this distance let the system apply real scale to the map.

**Comment by ghost** [comment]
I was convinced.

I independently modified orbslam 2 for use with Fisheye stereo camera. And while calibration of opencv 's fisheye occasionally produces an error, there was a case where a solution could be obtained properly. Using orbslam2 with that parameter, the scale is always 10% larger than the actual scale in any environment. Although the scale has errors, the shape of the map was very accurate.

Can the biggest cause be considered as calibration accuracy? In other threads, you mentioned in the past as follows.
  >I couldn't get opencv's calibration application for fisheye, so I calibrate it "by hand": put a trackbar for 
  >each undistortion parameter, and move them until image is calibrated. 

Is there a possibility that it is better to calibrate manually?

By the way, during calibration, I shoot a calibration board ahead 2 meters, but in the facility where I would like to run SLAM, most of the feature points will be 10 meters or more ahead. (There is no patterned object at short distance.)

**Comment by AlejandroSilvestri** [comment]
@takuhara , about calibration, it would be great if you can see the undistortioned images and judge for yourself if they seem to be fine.  In many cases automatic calibration parameters led to huge errors and horrible undistortioned images.

The main concern with fisheye lenses are the center coordinates.  If you correctly find them, probably your calibration is done.

Calibration is done one camera at the time, even for stereo cameras.  So, calibration is monocular, and monocular is not scale aware, so the distance to the pattern doesn't affect the calibration.

But the parallax can mess your scale.  If the distance between cameras is to small compared with the distance to the points in the scene, depth error increase.  Only theoretically because I don't have experience with stereo slam.

**Comment by ghost** [comment]
thank you.

**Comment by BristolVisualPFT** [comment]
@takuhara I have the same issue of having scaling using wide fov stereo cameras. Have you been able to solve the issue by any means? Thanks.
