### ISSUE TITLE
Camera rotation

### ISSUE THREAD

**Issue by KyleVSlotboom** [AlejandroSilvestri/os1#7]
I know this is a internal problem with monocular SLAM in general and cannot be fixed with software. But can this problem be eliminated by adding a 180 degree lens so that the camera recognizes more points during rotation?

And if so in which way or how extensive would the source code need to be adjusted in order to mitigate the distortion (flattening) created in the created map?

**Comment by AlejandroSilvestri** [comment]
@KyleVSlotboom ,

Pure rotations doesn't allow new points triangulation, so you enter a new and uncharted zone without known points to serve as reference.

Visual SLAM endure pure rotation when a minimum set of already mapped points still appear on image.  Thus, wider cameras let you rotate bigger angles without losing track.

I must tell you: it is not about recongnizing more features in image, because during pure rotation visual slam is unable to triangulate new points.  It's about keep tracking of known 3D points, don't letting them to go out of seeing.


Visual slam generate only one type of distortion in map: drifting.  The only way widely available to mitigate this kind of distortion is loop closing.

Perhaps you are experiencing distortion from uncalibrated camera.  Uncalibrated camera may let you use visual slam, but 3d points are wrongly triangulated.  I leave you 2 Youtube videos of OS1 applied no the same video taken with a 180º camera, processed twice with two different distortion methods.  You'll see wall point forming a rounded wall in one of them (the actual wall is flat), and a flat wall in the other.

- Poor calibration (wrong algorithm) https://youtu.be/wqnJwjqRgko?t=2m2s
- Better calibration (right algorithm) https://youtu.be/3hW5if_m2Yw?t=1m28s

It's not easy to see.  I'm sorry I don't have a better example.
